### ISSUE TITLE
[Feature Request] Show descriptions of command

### ISSUE THREAD

**Issue by seagle0128** [Yevgnen/ivy-rich#32] opened 2018-06-26 04:18 UTC
It's useful to show descriptions while using `counsel-M-x`. The feature should be like this:

![screenshot at 2018-06-26 12-15-31](https://user-images.githubusercontent.com/140797/41888980-b761c65a-793a-11e8-8ffd-f2f51435c0e0.png)

Reference: https://github.com/casouri/ivy-filthy-rich.

**Comment by Yevgnen** [comment] 2018-07-03 02:14
Seems pretty nice. I'll work on it soon!

**Comment by seagle0128** [comment] 2018-07-03 03:29
Thanks. I also suggest to add a minor mode to enable/disable easily.

**Comment by Yevgnen** [comment] 2018-07-04 04:00
@seagle0128 The minor mode is coming with the next elpa build. Let me know if you find any problem!

**Comment by seagle0128** [comment] 2018-07-04 09:00
@Yevgnen I tried the `ivy-rich-mode`, and it works well. But I think you should add `###autoload` to it, right?

And I summary the requirements here.
1. Show commands descriptions in `counsel-M-x`.
1. Show commands shortcuts in `counsel-M-x` as the original transformer.
1. Customize faces. The buffer names are too dark in some themes, e.g. `doom-molokai`.

![screenshot at 2018-07-04 16-58-25](https://user-images.githubusercontent.com/140797/42267441-98060fd8-7fab-11e8-86a0-d2e2ca9d144b.png)

**Comment by Yevgnen** [comment] 2018-07-04 11:04
Oh, my bad.

I am thinking about the customization for displaying columns. As long as
it’s done, it should be easy to achieve the requirements.

**Comment by seagle0128** [comment] 2018-07-04 11:32
Seems I spoke to soon. The minor mode has one issue here. `disable ivy rich` doesn't work...

**Comment by Yevgnen** [comment] 2018-07-05 01:31
Do you mean `(ivy-rich-mode -1)`? It should restore the original display transformer before enabling the minor mode, but not necessary be `ivy-switch-buffer-transformer` for `ivy-switch-buffer`.

**Comment by seagle0128** [comment] 2018-07-05 03:10
I recorded the screen for reference.

![peek 2018-07-05 11-09](https://user-images.githubusercontent.com/140797/42300634-fe1ebd40-8043-11e8-8205-7d90ce77a8d2.gif)

**Comment by Yevgnen** [comment] 2018-07-05 09:40
Strange. Can you please check `ivy-rich--original-display-transformers-list` and `ivy--display-transformers-list` before and after enabling or disabling the minor mode? 

Also there's a test branch `customize` implements the features you requested. Note that some function like supports for virtual buffers are current disabled. You can currently see the doc string of `ivy-rich--display-transformers-list` for brief description of how to use it. Suggestions are welcome.

**Comment by seagle0128** [comment] 2018-07-05 13:30
I checked the variables before and after enabling/disabling.

Enable:
``` elisp
(ivy-switch-buffer ivy-rich-switch-buffer-transformer)

(counsel-find-file ivy-read-file-transformer read-file-name-internal ivy-read-file-transformer ivy-switch-buffer ivy-rich-switch-buffer-transformer internal-complete-buffer ivy-switch-buffer-transformer counsel-describe-variable counsel-describe-variable-transformer counsel-describe-function counsel-describe-function-transformer counsel-M-x counsel-M-x-transformer counsel-git-grep counsel-git-grep-transformer counsel-ag counsel-git-grep-transformer counsel-rg counsel-git-grep-transformer counsel-projectile-find-file counsel-projectile-find-file-transformer counsel-projectile-switch-to-buffer counsel-projectile-switch-to-buffer-transformer counsel-projectile-grep counsel-projectile-grep-transformer counsel-projectile counsel-projectile-transformer)
```

Disable:
```elisp
nil

(counsel-find-file ivy-read-file-transformer read-file-name-internal ivy-read-file-transformer ivy-switch-buffer ivy-rich-switch-buffer-transformer internal-complete-buffer ivy-switch-buffer-transformer counsel-describe-variable counsel-describe-variable-transformer counsel-describe-function counsel-describe-function-transformer counsel-M-x counsel-M-x-transformer counsel-git-grep counsel-git-grep-transformer counsel-ag counsel-git-grep-transformer counsel-rg counsel-git-grep-transformer counsel-projectile-find-file counsel-projectile-find-file-transformer counsel-projectile-switch-to-buffer counsel-projectile-switch-to-buffer-transformer counsel-projectile-grep counsel-projectile-grep-transformer counsel-projectile counsel-projectile-transformer)
```

![ivy-rich](https://user-images.githubusercontent.com/140797/42326079-ad4a1746-809a-11e8-95a0-7c773010d0b3.gif)

**Comment by Yevgnen** [comment] 2018-07-06 01:15
The `ivy-rich--original-display-transformers-list` is a bit strange since it has `ivy-*rich*-switch-buffer-transformer` for `ivy-switch-buffer`. Did you forget to remove `(ivy-set-display-transformer 'ivy-switch-buffer 'ivy-rich-switch-buffer-transformer)` somewhere before enabling the minor mode?

Since disabling the minor will only restore the transformer to what it was before enabling the minor mode, but it is not necessary to be `ivy-switch-buffer-transformer` for `ivy-switch-buffer`.

**Comment by Yevgnen** [comment] 2018-07-06 01:18
By the way, the testing branch with customizable columns for transformers looks like e.g. for `counsel-M-x`

<img width="752" alt="screen shot 2018-07-06 at 9 17 00 am" src="https://user-images.githubusercontent.com/16749790/42355028-64a0dd1e-80fd-11e8-8a66-b265733f50c8.png">

**Comment by seagle0128** [comment] 2018-07-06 05:05
@Yevgnen The screenshot looks great! That's what's expected. 

Regarding `ivy-rich--original-display-transformers-list`, I am thinking if it's related to `desktop-mode` or something else. I will do some tests as well.

**Comment by seagle0128** [comment] 2018-07-06 13:12
I fixed this issue, I think. Perhaps the hook brought some side-effects, with other ivy configuration?
Anyway, `ivy-rich-mode` works fine.

I changed
```elisp
  (use-package ivy-rich
    :hook (ivy-mode . ivy-rich-mode)
    :config
    (setq ivy-virtual-abbreviate 'full
          ivy-rich-switch-buffer-align-virtual-buffer t
          ivy-rich-path-style 'abbrev))
```
to
```elisp
  (use-package ivy-rich
    :init (ivy-rich-mode 1)
    :config
    (setq ivy-virtual-abbreviate 'full
          ivy-rich-switch-buffer-align-virtual-buffer t
          ivy-rich-path-style 'abbrev))
```

**Comment by seagle0128** [comment] 2018-07-08 14:07
I've been tested `customization` branch for 2 days. It's working fine .

**Comment by Yevgnen** [comment] 2018-07-09 01:21
@seagle0128 Thanks for the feedback!

**Comment by seagle0128** [comment] 2018-07-09 06:07
@Yevgnen Welcome! It's really cool and I'm eager getting from MEPLA. Thank you!

**Comment by seagle0128** [comment] 2018-07-10 16:47
@Yevgnen I found an issue for `customize` branch. Please take a look.

`C-h v` for this function:
```elisp
(defvar-local doom-modeline-percent-position
  "Specification of \"percentage offset\" of window through buffer.
See `mode-line-percent-position'."
  (or (bound-and-true-p mode-line-percent-position) '(-3 "%p")))
```
I got this exception:
```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp (-3 "%p"))
  string-match("^\\(.+\\)\\([\015\n]\\)?" (-3 "%p"))
  ivy-rich-counsel-variable-docstring("doom-modeline-percent-position")
  ivy-rich-format-column("doom-modeline-percent-position" (ivy-rich-counsel-variable-docstring (:face font-lock-doc-face)))
  #f(compiled-function (column) #<bytecode 0x41183191>)((ivy-rich-counsel-variable-docstring (:face font-lock-doc-face)))
  mapconcat(#f(compiled-function (column) #<bytecode 0x41183191>) ((counsel-describe-variable-transformer (:width 40)) (ivy-rich-counsel-variable-docstring (:face font-lock-doc-face))) " ")
  ivy-rich-format("doom-modeline-percent-position" ((counsel-describe-variable-transformer (:width 40)) (ivy-rich-counsel-variable-docstring (:face font-lock-doc-face))) " ")
  ivy-rich--counsel-describe-variable-transformer("doom-modeline-percent-position")
  mapcar(ivy-rich--counsel-describe-variable-transformer ("doom-modeline-enable-word-count" "doom-modeline-env-command" "doom-modeline-env-version" "doom-modeline-fn-alist" "doom-modeline-height" "doom-modeline-percent-position" "doom-modeline-remap-face-cookie" "doom-modeline-var-alist" "doom-modeline-vspc"))
...
 counsel-describe-variable()
  funcall-interactively(counsel-describe-variable)
  call-interactively(counsel-describe-variable nil nil)
  command-execute(counsel-describe-variable)
```

**Comment by Yevgnen** [comment] 2018-07-11 01:20
@seagle0128 I can confirm this. The signature of `defvar-local` is `(defvar-local VAR VAL &optional DOCSTRING)`. I think this definition place the docstring into the wrong position?

```elisp
(defvar-local doom-modeline-percent-position
  (or (bound-and-true-p mode-line-percent-position) '(-3 "%p"))
  "Specification of \"percentage offset\" of window through buffer.
See `mode-line-percent-position'.")
```

**Comment by seagle0128** [comment] 2018-07-11 06:33
@Yevgnen My bad... Sorry for that.

**Comment by Yevgnen** [comment] 2018-07-12 01:00
@seagle0128 Never mind!

**Comment by seagle0128** [comment] 2018-07-15 06:49
@Yevgnen I think `ivy-rich` is stable enough to merge the master branch. Your opinion?

**Comment by seagle0128** [comment] 2018-08-14 14:28
Gental ping...

**Comment by Yevgnen** [comment] 2018-08-28 03:37
Merged now~

**Closed by Yevgnen** 2018-08-28 03:37 UTC
